title: Blog
owner: Eilleen Zhang
email: hello@eilleeenz.com
description: Eilleen Zhang's Blog. Contact me at hello@eilleeenz.com!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.eilleeenz.com" # the base hostname & protocol for your site, e.g. http://example.com
language: en
twitter_username: eilleeenz
github_username:
disqus_username: 
# Build settings
markdown: kramdown
theme: minima

permalink: /:year/:month/:day/:title/

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/bundle
excerpt_separator: <!--more-->
